version: '3.8'
services:
  react-app:
    build:
      context: .
      dockerfile: .Dockerfile
    image: baonhat20/landingpage-project:latest
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      - ./nginx.config:/etc/nginx/conf.d/default.conf